services:
  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: 5iw2-nest-api
    ports:
      - 8000:8000 # API
      - 9229:9229 # Debugging
    command: >
      sh -c "
        npx prisma migrate dev --name init --preview-feature &&
        npm run start:dev
      "
    env_file:
      - ./back/.env
    volumes:
      - ./back:/app
      - /app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: 5iw2-nest-frontend
    ports:
      - 3000:3000
    env_file:
      - ./front/.env
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - api

  adminer:
    image: adminer
    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: 5iw2-nest-db
    env_file:
      - ./back/.env
    volumes:
      - 5iw2-nest:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  5iw2-nest: {}
